### ISSUE TITLE
`htfOpts` not exposed in type definitions

### ISSUE THREAD

**Issue by felixbrucker** [paulmillr/noble-curves#101]
It seems like `htfOpts` is missing in the type definitions. I use `verifyBatch` of `bls12-381` which has a 4th param, as seen here: https://github.com/paulmillr/noble-curves/blob/2f1460a4d7f31e5a61db9606266f5b9a5c659c9d/src/abstract/bls.ts#L423
however in the type definitions it is missing: https://github.com/paulmillr/noble-curves/blob/2f1460a4d7f31e5a61db9606266f5b9a5c659c9d/src/abstract/bls.ts#L99

I'm using this to verify using a different DST other than the default one.

The same seems to be true for other methods with `htfOpts` as well.

The current workaround is to let typescript ignore the error like so:
```ts
    ...
    // @ts-expect-error untyped options
    { DST: 'BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_AUG_' },
```

**Comment by paulmillr** [comment]
would you care to submit a pr ?

**Comment by felixbrucker** [comment]
I would but i can't properly check out the repo on windows because of some test files/fixtures
I will report that error separately

**Comment by paulmillr** [comment]
@felixbrucker fixed it, please submit a pull req asap, for it to be included in mid-dec release.

**Comment by felixbrucker** [comment]
Ah you already fixed it, thanks 👍
