### ISSUE TITLE
Fp2.eql

### ISSUE THREAD

**Issue by vincenzoiovino** [paulmillr/noble-curves#104]
Hello,
first of all thanks for this nice library.
I tried to use Fp2.eql but does not work.
I use version 1.2.0.
It always returns true  even if the points are different. 
Currently I need to use .toHex() and then compare them as strings.

Any clue on whether this is a bug or a misunderstanding/misuse of the library of mine?

**Comment by paulmillr** [comment]
```
> Fp2.eql(Fp2.ZERO, Fp2.ONE)
false
```
