### ISSUE TITLE
Donating Funds to Noble-Curves

### ISSUE THREAD

**Issue by Lfada** [paulmillr/noble-curves#108]
Hi Noble-Curves maintainers. I'm Lucas, a core contributor to the [Drips](https://www.drips.network/) project. I help recipients of donations through their learning and onboarding process.

[Ethers.JS](https://twitter.com/ethersproject) has been using https://github.com/paulmillr/noble-curves. It's in fact one of their most critical dependencies!

Ethers.JS core contributors (mostly RicMoo) appreciate the work you all do and want to make sure that you are all well-funded to keep doing it. For that reason, they have decided to donate some funds to your project through [Drips](https://www.drips.network/)

Who can I talk to about it?

cc: @paulmillr, @randombit, @sublimator

**Comment by paulmillr** [comment]
@Lfada i’m sole maintainer of the project. Just ping me via email or x.

**Comment by sublimator** [comment]
Lol, i was so close!!
