### ISSUE TITLE
What is the difference between getSharedSecret and ECDH_compute_key

### ISSUE THREAD

**Issue by aegorx** [paulmillr/noble-curves#113]
The shareKey generated by using p256.getSharedSecret does not match the sharekey generated by OpenSSL ECDH_compute_key, nor does it match the sharekey generated by using subarray(1).

**Comment by paulmillr** [comment]
I have no idea. noble multiplies point B by secret scalar A, which is the general definition of shared secret / ecdh. It must always be the same between all implementations.

Ensure the output is compressed / uncompressed depending on your needs.

https://github.com/paulmillr/noble-curves/blob/a1a7dc9cbf4ad0630339c085c81482cb2e0b685a/src/abstract/weierstrass.ts#L921-L926
