### ISSUE TITLE
Bundling related issues

### ISSUE THREAD

**Issue by aulneau** [paulmillr/noble-curves#13]
`@noble/curves` does not work correctly in react-native. However, `@noble/hashes` does. I believe the reason this is the case is due to an issue around the export maps in each project.

In `@noble/curves` it's the case that the export map [includes the `lib` folder](https://github.com/paulmillr/noble-curves/blob/main/package.json#L40), whereas in `@noble/hashes`, they are within [the root of the library](https://github.com/paulmillr/noble-hashes/blob/main/package.json#L45).

I have also ran into this issue with my own libraries, and have been forced to ensure the `package.json` lives along side the built assets when the library has more advanced export maps.

I would suggest that `@noble/curves` follows the same build set up as `@noble/hashes`.

**Comment by paulmillr** [comment]
fixed, react native is shit

**Comment by pke** [comment]
@paulmillr I am still encountering 

```
warn Package @noble/curves has been ignored because it contains invalid configuration. Reason: Package subpath './package.json' is not defined by "exports" in /Users/pkursawe/projects/release/app/node_modules/@noble/curves/package.json
```

**Comment by paulmillr** [comment]
>Package subpath './package.json' is not defined

that seems weird, because we don’t require package.json in our files
