### ISSUE TITLE
Access to Fp types and finalExponentiate method

### ISSUE THREAD

**Issue by Wagalidoom** [paulmillr/noble-curves#136]
Hi,

I'm trying to access the finalExponentiate method from Fp12 (screenshot below) but i ran into a typescript error. I'm using typescript v5.4.5.

![image](https://github.com/paulmillr/noble-curves/assets/43578243/9baecbfb-8e4c-4d3c-9eff-d71c21b1fd2a)

![image](https://github.com/paulmillr/noble-curves/assets/43578243/ae78328f-139f-44ef-bae7-96df121daa2b)

Do you have any ideas how to solve this? Thank you.

**Comment by paulmillr** [comment]
Use ts-ignore for now, will fix later
