### ISSUE TITLE
Private key normalized twice in schnorrGetExtPubKey

### ISSUE THREAD

**Issue by mahnunchik** [paulmillr/noble-curves#14]
Private key normalized twice in `schnorrGetExtPubKey` method:

1. Direct normalization https://github.com/paulmillr/noble-curves/blob/main/src/secp256k1.ts#L118
2. Inside `Point.fromPrivateKey` method https://github.com/paulmillr/noble-curves/blob/main/src/secp256k1.ts#L119

https://github.com/paulmillr/noble-curves/blob/b1f50d936412320b7d8800352fc0768cb0b9b029/src/abstract/weierstrass.ts#L290

**Comment by paulmillr** [comment]
Yeah. Schnorr requires returning scalars (d). Scalars are produced by normalization. fromPrivateKey does normalization but does not return scalar.

Passing normalized scalar to the normalize function is fast and not a big deal.
