### ISSUE TITLE
Buffer is not an instance of Uint8Array in jsdom unlike nodejs

### ISSUE THREAD

**Issue by mahdiyari** [paulmillr/noble-curves#145]
The following fails in jsdom when the key is Buffer:
```
secp256k1.getPublicKey(key)
```

The issue happens on jsdom environment and is related to [this line](https://github.com/paulmillr/noble-curves/blob/342603712ebe210bdd1be984e9b24609f5035fdf/src/abstract/utils.ts#L21)
It turns out Buffer is not an instance of Uint8Array in jsdom. I don't know if it is a jsdom issue or not but might be fixable here somehow. Maybe checking if it can be converted into hex with .toString('hex') or if constructor name is Buffer.

**Comment by paulmillr** [comment]
You should drop Buffer. It's really bad:

- node.js only, not available in browsers
- Completely different semantics from Uint8Array: slice() does mutable subarray()
- Security issue: all nodejs-allocated buffers are available to any code through global variable

**Comment by mahdiyari** [comment]
Thanks I'll consider it.
