### ISSUE TITLE
[question] Create curve from explicit parameters

### ISSUE THREAD

**Issue by li0ard** [paulmillr/noble-curves#160]
Hello Paul, I am trying to do ePassport verification using your module. Security Object of Document (PKCS#7) contains an X509 certificate with explicit curve parameters:
![image](https://github.com/user-attachments/assets/6d71715c-6ffc-4e2a-a2d4-ae16679108cd)
Here we can see the `p` field, by which we can determine that it is P256. 
When I create a curve class using the `createCurve` method and call the `verify` method I get `false`, however if I call the same method on the `p256` class I get `true` back. How can I fix this?

**Comment by paulmillr** [comment]
> How can I fix this?

I have no idea. You need to provide the exact code you're doing. And before providing the code, two questions:

1. Why can't you just use P256 that we export?
2. What is the exact difference between your code and exported P256? Maybe walk through it and look up for the bugs

**Comment by li0ard** [comment]
1. Because I follow ICAO standard 9303 (p.12), which states that:
> Those issuing States or organizations implementing ECDSA for signature generation or verification SHALL use [X9.62]
or [ISO/IEC 15946]. The elliptic curve domain parameters used to generate the ECDSA key pair MUST be described
explicitly in the parameters of the public key, i.e. parameters MUST be of type ECParameters (no named curves, no
implicit parameters) and MUST include the optional co-factor. ECPoints MUST be in uncompressed format.

So it's easier to create custom curve each time.

2. Only the `lowS` parameter in the `curveDef` argument. But I tried changing it, and I still get `false`

**Comment by li0ard** [comment]
I fixed this using the `normalizeS` method in the `Signature` class.

Code:
```ts
let sigObj = curve.Signature.fromDER(sig)
let result = curve.verify(sigObj.normalizeS(), dataToCheck, pk)
```
