### ISSUE TITLE
Angular doesn't find "crypto" module.

### ISSUE THREAD

**Issue by ElleLeonne** [paulmillr/noble-curves#162]
```
✘ [ERROR] Deployment failed!

  Failed to publish your Function. Got error: Uncaught Error: No such module
  "crypto".
```

I'm encountering an issue when attempting to import and use the package in an angular application hosted on Cloudflare.

This issue only occurs when I attempt to import and then use any of the curve algorithms (eg: "import { secp256k1 } from '@noble/curves/secp256k1'" followed by, for example, secp256k1.create().

I'm curious why this isn't using the natively compiled WebCrypto, when I call crypto.subtle just fine.

**Comment by paulmillr** [comment]
Something is wrong with your build tool / env. Report it to their repository.
