### ISSUE TITLE
Documenting the expected behavior when one of the inputs is zero for batchInvert

### ISSUE THREAD

**Issue by kevaundray** [paulmillr/noble-curves#17]
The current behavior when a value is 0 in batchInvert is to return undefined for that element. It would be good to document this behavior on top of the batchInvert method.

**Comment by kevaundray** [comment]
It also seems that the non batched version of invert will panic on zero, if I'm understanding correctly:

```
  if (number === _0n || modulo <= _0n) {
    throw new Error(`invert: expected positive integers, got n=${number} mod=${modulo}`);
  }
```

**Comment by paulmillr** [comment]
Document where?

**Comment by paulmillr** [comment]
It's reasonable. It should be undefined or error since inverse doesn't exist.

**Comment by kevaundray** [comment]
Right, I'm not commenting on whether it's reasonable, just that it would be good to have it documented, preferably on top of the function?

Though as commented above, batchInvert and Invert seem to have different behaviour on zero, what was the rationale behind this?

**Comment by paulmillr** [comment]
>Though as commented above, batchInvert and Invert seem to have different behaviour on zero, what was the rationale behind this?

Performance reasons and easier testing

**Comment by paulmillr** [comment]
done
