### ISSUE TITLE
hash-to-curve: hash_to_field expand cannot be undefined

### ISSUE THREAD

**Issue by armfazh** [paulmillr/noble-curves#18]
Note that in [bls12-381](https://github.com/zkcrypto/bls12-381/) Scalar implements HashToField. So this is the method to test, not the utility method `from_okm`.

https://github.com/paulmillr/noble-curves/blob/4b2d31ce7f0f2ce217243a77e5723d774da32212/test/bls12-381.test.js#L856-L867

**Comment by paulmillr** [comment]
Are you talking about this method?

https://github.com/zkcrypto/bls12_381/blob/7de7b9d9c509b9973b35a3241b74bbbea95e700a/src/hash_to_curve/map_scalar.rs#L15

**Comment by armfazh** [comment]
no, talking about this one

https://github.com/zkcrypto/bls12_381/blob/7de7b9d9c509b9973b35a3241b74bbbea95e700a/src/hash_to_curve/mod.rs#L44
