### ISSUE TITLE
Support groestl

### ISSUE THREAD

**Issue by gruve-p** [paulmillr/noble-curves#19]
Groestl was a sha-3 candidate: https://github.com/Groestlcoin/groestl-hash-js

Reasons we want groestl added on noble-hashes:

1. We have our own [bip32 fork](https://github.com/Groestlcoin/bip32grs). Recently you send a [PR](https://github.com/bitcoinjs/bip32/pull/71) and we no longer can merge the changes from upstream without getting on noble-hashes first.
2. We have our own [wif fork](https://github.com/Groestlcoin/wifgrs). Recently you send a [PR](https://github.com/bitcoinjs/wif/pull/30) and we no longer will be able to merge the changes from upstream without getting on noble-hashes first.
3. We have our own [bs58check fork](https://github.com/Groestlcoin/bs58grscheck). Recently you send a [PR](https://github.com/bitcoinjs/bs58check/pull/41) and we no longer can merge the changes from upstream.
4. We have our own [bitcoinjs-lib fork](https://github.com/Groestlcoin/groestlcoinjs-lib). Recently you send a [PR](https://github.com/bitcoinjs/bitcoinjs-lib/pull/1879) and we no longer can merge the changes from upstream.

**Comment by paulmillr** [comment]
If you maintain this many forks, you could fork noble-hashes and add groestl to your fork. What's the benefit of using hash no one uses?
