### ISSUE TITLE
Problem importing in a TS project

### ISSUE THREAD

**Issue by dhruvkelawala** [paulmillr/noble-curves#2]
While trying to import stark curve (or any other) from **micro-curve-definitions** package. Seems like the project isn't build properly as there is no build directory and also no entry file (index.js).

`Cannot find module 'micro-curve-definitions' or its corresponding type declarations.` TS throws this error even after properly installing the package

<img width="267" alt="Screenshot 2022-12-15 at 13 10 01" src="https://user-images.githubusercontent.com/50968441/207867404-6705a0d2-2f74-477c-8a22-9337c9eeca01.png">

This is what the package looks like in node_modules

**Comment by paulmillr** [comment]
Fixed now I guess
