### ISSUE TITLE
edwards: ZIP215 or NIST validation?

### ISSUE THREAD

**Issue by paulmillr** [paulmillr/noble-curves#23]
https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-186.pdf new spec that defines edwards curves says point x, y must be < CURVE.p. ZIP215, spec for consensus-critical apps, says x, y can be > CURVE.p (but less than 2^256).

Need to understand what's the best decision here. ExtendedPoint.fromHex already has `strict` option which implements behavior from NIST spec. I guess `verifyStrict` should be added now.

as per @tarcieri

**Comment by tarcieri** [comment]
Per https://github.com/dalek-cryptography/curve25519-dalek/issues/380 we're considering supporting both the ZIP-215 and NIST validation rules, with the former as the default and the latter as a "strict" variant

**Comment by paulmillr** [comment]
113d906233cd3a1a4f70ca2c37970c6dd5cacda0

**Comment by paulmillr** [comment]
We will likely use more descriptive verification option naming:

```ts
ed25519.verify(sig, msg, pub); // Default mode: follows ZIP215
ed25519.verify(sig, msg, pub, { zip215: false }); // RFC8032 / FIPS 186-5
```

`strict: true` seems unclear.

**Comment by tarcieri** [comment]
Nice! That seems good
