### ISSUE TITLE
bls_12_381 CURVE.G2.fromBytes mutates input

### ISSUE THREAD

**Issue by blazmrakgid** [paulmillr/noble-curves#24]
This is a minor inconvenience and unexpected. All of the APIs seem to not mutate the input, but the CURVE.G2.fromBytes does, so running it twice on the same input fails.

**Comment by paulmillr** [comment]
You shouldn't use `CURVE.G2.fromBytes`, this is internal. Use `G2.fromHex` instead.

I will need to hide the internal methods to prevent misuse.

**Comment by paulmillr** [comment]
Done

**Comment by blazmrakgid** [comment]
Well... fuck me, I shot myself in the head with this one :D functions on the CURVE can be super useful for doing curve operations yourelf, because they have stuff like finalExponentiation on Fp12, fromBytes, etc. I implemented BBS+ and had to resort to them in a couple of places. Please leave it public, just disclaim that when using CURVE, you are on your own.

**Comment by paulmillr** [comment]
@blazmrakgid which functions? Fp, Fp2, Fp12, G1, G2 are available in top-level namespace. There is no need to write CURVE.G2 when you can just write G2.

**Comment by blazmrakgid** [comment]
There are some functions only on curve (Fp12.finalExponentiate for example). Looking at it, it might be the only one that I need... I got confused by `fromHex`, because I would expect a hex string to go in, but it takes both hex string and bytes 🤷

**Comment by paulmillr** [comment]
`bls.pairing` function has optional third argument `withFinalExponent: boolean = true`.

Would it solve your use case?

**Comment by paulmillr** [comment]
>Yes, that would be one solution, but I think it is slower doing it twice (once for each side)?

No, the speed should be the same.

In fact many algorithms do exactly this: they execute non-final-exp part for everything and then execute final exp just once for all

**Comment by blazmrakgid** [comment]
Then I misunderstood how you meant me to use it. What I mean is this:

```javascript
const left = pairing(left1, left2, true)
const right = pairing(right1, right2, true)

left == right
```

meaning final-exp runs twice. Am I missing something?

**Comment by paulmillr** [comment]
just use `false`, not true.

**Comment by blazmrakgid** [comment]
We have gone full circle now 😄 If I use false, then i need Fp12.finalExponentiate(), which is only available on the CURVE.Fp12 😄

**Comment by paulmillr** [comment]
```
const left = pairing(left1, left2, false)
const right = pairing(right1, right2, false)
pairing(left, right, true)
```

**Comment by blazmrakgid** [comment]
But pairing takes G1 and G2, not Fp12, which is the result of pairing(...)?

**Comment by paulmillr** [comment]
Right...will think of something. Don't worry,

**Comment by paulmillr** [comment]
```ts
const Fp12 = bls.fields.Fp12;
const left = pairing(left1, left2, false)
const right = pairing(right1, right2, false)
Fp12.finalExponentiate(left, right)
```
