### ISSUE TITLE
Bls point addition algorithm correctness

### ISSUE THREAD

**Issue by blazmrakgid** [paulmillr/noble-curves#28]
Disclaimer: This might not be an issue with the library, however, I have no other explanation atm. 

I have implemented the point addition for BLS curves on my own using an algorithm from hyperelliptic (https://www.hyperelliptic.org/EFD/g1p/auto-shortw-jacobian-0.html, both 98 and 07 algo) and tried to match the result (Point.equals) with the algorithm used by Point and the result was not the same point. I then went through history and reused the previous implementation of Point.add, and it also failed.

Is this a bug or is it expected?

**Comment by paulmillr** [comment]
The library is correct, reason being: we have megabytes of deterministic test vectors for all kinds of curves including bls12-381 and other weierstrass curves.

Jacobian coordinates from the URL are different from projective / homogenous coordinates in which the library currently operates. You can't use `equals`, `add`, or anything else: they need to be re-implemented. That goes same for checking for torsion component and other functions.

So, rewriting in jacobian is possible, and should work, but is tricky, less safe; and is not our goal.
