### ISSUE TITLE
privacypass/challenge-bypass-extension

### ISSUE THREAD

**Issue by sublimator** [paulmillr/noble-curves#29]
https://github.com/privacypass/challenge-bypass-extension/issues/391

@paulmillr ^^ :)

**Comment by paulmillr** [comment]
You could submit a pr but i don't think they're interested

**Comment by sublimator** [comment]
> it's cloudflare

Not sure the implications there :)

**Comment by sublimator** [comment]
Ha, just stumbled upon this:
https://github.com/cloudflare/voprf-ts/pull/26

Maybe a communications issue
