### ISSUE TITLE
Problem importing in a TS project - 2

### ISSUE THREAD

**Issue by dhruvkelawala** [paulmillr/noble-curves#3]
This is similar to #2 with a different import error

`node_modules/micro-curve-definitions/lib/index.d.ts' is not a module.ts(2306)`

Edit: Can be fixed using `import { keccak, pedersen } from 'micro-curve-definitions/lib/stark';` but then it causes the following build error

```
✘ [ERROR] Could not resolve "@noble/curves/weierstrass"

    node_modules/micro-curve-definitions/lib/stark.js:6:28:
      6 │ import { weierstrass } from '@noble/curves/weierstrass';
        ╵                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The path "./weierstrass" is not exported by package "@noble/curves":

    node_modules/micro-curve-definitions/node_modules/@noble/curves/package.json:34:13:
      34 │   "exports": {
         ╵              ^

  You can mark the path "@noble/curves/weierstrass" as external to exclude it from the bundle, which
  will remove this error.
```

**Comment by paulmillr** [comment]
I think this is a problem with your build system.

**Comment by dhruvkelawala** [comment]
Closing this as resolved. Thanks for helping.

**Comment by dsawali** [comment]
sorry to necro this post, but @dhruvkelawala I am seeing this same error but for BLS curve. How were you able to resolve it?

**Comment by paulmillr** [comment]
play with moduleResolution node16 or something
