### ISSUE TITLE
toDERHex incompatible with other libs

### ISSUE THREAD

**Issue by filefilegoadmin** [paulmillr/noble-curves#30]
Hi,

I am trying to use this module in the browser, and we have a backend which runs golang with "go-libp2p/core/crypto/key.go"  using `secp256k1`.

The problem is when I sign a message using noble-curves and export the sig using toDERHex, in libp2p (they are using DER) the verification fails without error.

Same private key is used btw

**Comment by filefilegoadmin** [comment]
This is where the sig is serialized: `https://github.com/libp2p/go-libp2p/blob/master/core/crypto/secp256k1.go#L81`

**Comment by paulmillr** [comment]
Here's actual source code of their verify function for the record:

https://github.com/decred/dcrd/blob/b4fab9efd838469f718fc943f2f19828d7829b49/dcrec/secp256k1/ecdsa/signature.go#L163

**Comment by paulmillr** [comment]
I suggest executing `ParseDERSignature` from their library on your noble signature and seeing which error it throws.

**Comment by jrick** [comment]
libp2p is implicitly using sha256 https://github.com/libp2p/go-libp2p/blob/master/core/crypto/ecdsa.go#L136

**Comment by paulmillr** [comment]
use `prehash: true`
