### ISSUE TITLE
Encrypt/Decrypt Functionality?

### ISSUE THREAD

**Issue by Srayman** [paulmillr/noble-curves#34]
First, I want to mention this repository is great!  It helped improve the performance of sign/verify using p256 compared to another library we were using.  

I wanted to ask if you have any plans to implement encrypt and decrypt methods? 

We are using [ecies-25519](https://www.npmjs.com/package/ecies-25519) for encrypt/decrypt with ed25519 and the performance is good.  However for [p256](https://www.npmjs.com/package/@safeheron/crypto-ecies) and [secp256k1](https://www.npmjs.com/package/ecies-geth) the performance is quite a bit slower in the libraries we are using and are looking at alternatives.

**Comment by paulmillr** [comment]
There are no plans in adding any encryption functionality to the library, which is limited to elliptic curve stuff.

It would be great to have, but in a different library.
