### ISSUE TITLE
CommonJs for micro-curve-definitions

### ISSUE THREAD

**Issue by penovicp** [paulmillr/noble-curves#4]
The `micro-curve-definitions` module is published with only `esm` files. It would be beneficial to also include `cjs` builds so both formats can be supported the same way it is done for `@noble/curves`.

**Comment by paulmillr** [comment]
It includes both
Just need to publish new version

**Comment by paulmillr** [comment]
0.2.1 is out, try it

**Comment by penovicp** [comment]
The new version works. Thank you!

Just to mention two smaller things I noticed:
- Now that both builds are included for `micro-curve-definitions` it might be worthwhile to add `exports` definitions to `package.json` so the `cjs` and `esm` differentiation can be done automatically by module resolution
- The file `curve-definitions/src/ed448.ts` has a dependency `../../lib/montgomery.js` which I'm guessing should be for `@noble/curves/montgomery`

If these changes make sense to you I can also create a PR if you'd like.
