### ISSUE TITLE
How to use Schnorr over BN254 + Grumpkin

### ISSUE THREAD

**Issue by colinnielsen** [paulmillr/noble-curves#44]
Hello,
For context, I am working with the Noir lang and the Aztec protocol, which uses `bn254` and  `Grumpkin` curves, defined [here](https://hackmd.io/@aztec-network/ByzgNxBfd#Cryptography-Primitives).

How can I set up pairing on `bn254`? I am looking into how to set up a weierstrass instance of `bn254` with a `G2` pairing group so I can do aggregation - will this lib allow for that?

(amazing work btw, keep it up!)

**Comment by paulmillr** [comment]
Pairing has not been implemented on bn254 at this point.

**Comment by colinnielsen** [comment]
Gotcha, so I would have to create an instance of both curves, and use pairing functions directly?

**Comment by paulmillr** [comment]
Yeah, and I don't think bls pairing would work for bn. They are probably different? I didn't do a deep dive though.

**Comment by paulmillr** [comment]
yup
