### ISSUE TITLE
Remove utf8ToBytes definition

### ISSUE THREAD

**Issue by madeken** [paulmillr/noble-curves#52]
You already have the `utf8ToBytes` function in `noble-hashes` which this project depends on, so you might as well just use it and not redefine it here. Actually the project already is a bit of a mix between calling nobel-curves.utf8ToBytes and nobel-hashes.utf8ToBytes  (which isn't a big deal, as they do the same thing, but a bit weird?).

Anyway, not a big deal but I think it's cleaner and selfishly it allows me to only have to patch 1 library instead of 2 (since I'm running in an environment without TextEncoder)

**Comment by paulmillr** [comment]
Everything inside of `abstract` directory does not depend on hashes, on purpose.

Reason: user may opt-in into using their own hashing library.

This way, there would be no dependency on hashes.

Duplication is fine, it's only a couple functions.

**Comment by madeken** [comment]
Fair enough
