### ISSUE TITLE
Package version in dependent modules

### ISSUE THREAD

**Issue by mahnunchik** [paulmillr/noble-curves#63]
Modules dependent on `@noble/curves` uses `~` as version matcher. It produces many version of `@noble/curves` in dependencies tree:

```
├── @noble/curves@1.1.0
├─┬ @scure/bip32@1.3.0
│ └── @noble/curves@1.0.0
└─┬ @scure/btc-signer@1.0.1
  └── @noble/curves@1.0.0
```

https://github.com/paulmillr/scure-btc-signer/blob/e9fdfbc1fe8ce43efa384e1f433f72c21ce25562/package.json#L17-L20

I think that `^` can be used for own modules to reduce total bundle size.

Issue is also related to `@noble/hashes` and `@scure/base`

**Comment by paulmillr** [comment]
That was done on purpose. My aim is to have much higher supply chain security than most other packages on NPM. This means that if you depend on bip32@1.3, if my NPM account is hacked, you won't be affected by it.

So, this won't be changed.

This also forces to make releases less often. I don't want to release 1.3.0 and then 1.4.0 a few weeks later: there needs to be some time, because updating all dependents is tedious.

**Comment by mahnunchik** [comment]
@paulmillr if your account is hacked then modified patch version can be published. It will be matched by `~` and `^`.

So the solution doesn't resolve security issue but increases bundle size (there are 3 versions of `@noble/curves` in my project).

Alternative solution: update dependencies of `@scure/bip32`, `ed25519-keygen`, `micro-*-signer` more often.

**Comment by paulmillr** [comment]
>Alternative solution: update dependencies of @scure/bip32, ed25519-keygen, micro-*-signer more often.

yeah that sounds better

GitHub still doesn't allow me to update ed25519-keygen though

**Comment by mahnunchik** [comment]
I'm looking forward to have deps updated and new `ed25519-keygen` published.

**Comment by mahnunchik** [comment]
Currently `@noble/curves` depends on the exact version of the package `@noble/hashes`.

```json
"@noble/hashes": "1.6.0"
```

So at the moment we get two versions of `@noble/hashes`

```json
    "node_modules/@noble/curves": {
      "version": "1.7.0",
      "resolved": "https://registry.npmjs.org/@noble/curves/-/curves-1.7.0.tgz",
      "integrity": "sha512-UTMhXK9SeDhFJVrHeUJ5uZlI6ajXg10O6Ddocf9S6GjbSBVZsJo88HzKwXznNfGpMTRDyJkqMjNDPYgf0qFWnw==",
      "license": "MIT",
      "dependencies": {
        "@noble/hashes": "1.6.0"
      },
      "engines": {
        "node": "^14.21.3 || >=16"
      },
      "funding": {
        "url": "https://paulmillr.com/funding/"
      }
    },
    "node_modules/@noble/curves/node_modules/@noble/hashes": {
      "version": "1.6.0",
      "resolved": "https://registry.npmjs.org/@noble/hashes/-/hashes-1.6.0.tgz",
      "integrity": "sha512-YUULf0Uk4/mAA89w+k3+yUYh6NrEvxZa5T6SY3wlMvE2chHkxFUUIDI8/XW1QSC357iA5pSnqt7XEhvFOqmDyQ==",
      "license": "MIT",
      "engines": {
        "node": "^14.21.3 || >=16"
      },
      "funding": {
        "url": "https://paulmillr.com/funding/"
      }
    },
    "node_modules/@noble/hashes": {
      "version": "1.6.1",
      "resolved": "https://registry.npmjs.org/@noble/hashes/-/hashes-1.6.1.tgz",
      "integrity": "sha512-pq5D8h10hHBjyqX+cfBm0i8JUXJ0UhczFc4r74zbuT9XgewFo2E3J1cOaGtdZynILNmQ685YWGzGE1Zv6io50w==",
      "license": "MIT",
      "engines": {
        "node": "^14.21.3 || >=16"
      },
      "funding": {
        "url": "https://paulmillr.com/funding/"
      }
    },
```

@paulmillr  Please think again about using `~` in the version that allows installation of patch versions for packages published by you.

The probability that attackers will hack your account and publish a modified version of one package is approximately equal as all your packages.

**Comment by paulmillr** [comment]
I won't change it for the near future.

Curves update is coming ASAP with new hashes and other dependents would update as well.
