### ISSUE TITLE
Support of minimised signature size for BLS12-381 

### ISSUE THREAD

**Issue by DandelionNet** [paulmillr/noble-curves#64]
Will there be support for the variant of BLS with minimal signature size?

**Comment by paulmillr** [comment]
yeah, if someone contributes it

**Comment by paulmillr** [comment]
first 100 lines of https://github.com/paulmillr/noble-curves/blob/476e75104fa685827dd3cff81e95742e30017650/src/bls12-381.ts


https://github.com/paulmillr/noble-curves#resources

**Comment by terrysu64** [comment]
Thanks! Will take a look.
