### ISSUE TITLE
cannot use `finalExponentiate` with type safety

### ISSUE THREAD

**Issue by CluEleSsUK** [paulmillr/noble-curves#65]
In https://github.com/drand/drand-client we use the bls12-381 curve for verifying signatures created by our network.
We have a custom scheme that creates signatures on G1 rather than G2, and thus far have been performing our own pairing operations as demonstrated [here](https://github.com/drand/drand-client/blob/e31f33ae3cde16e69f2dea9417dd9a11af5c21e2/lib/beacon-verification.ts#L74).

With the newest curves version, it appears that `finalExponentiate` is on the type `Fp12Utils` [here](https://github.com/paulmillr/noble-curves/blob/476e75104fa685827dd3cff81e95742e30017650/src/bls12-381.ts#L551C12-L551C12) which is available on the `CurveType` type, which gets passed into the bls constructor [here](https://github.com/paulmillr/noble-curves/blob/476e75104fa685827dd3cff81e95742e30017650/src/bls12-381.ts#L1052). 
Unfortunately, as defines its own `fields` param, we can't use the `finalExponentiate` function directly, without casting to `any`. Other types we could cast it to are private, but even then casting feels a little ugly.

Is there another suggested way to use `finalExponentiate` directly or would it be possible to expose it?

Thanks for all your hard work! Your libraries have saved us a lot of pain!

**Comment by paulmillr** [comment]
Could you please describe what you've said in a few lines of code, to make it easier for me to understand?

**Comment by CluEleSsUK** [comment]
To use the finalExponentiate, one must do:
```
    const Fp12 = bls.fields.Fp12 as any;// as {finalExponentiate(num: any): any;};
    const exp = Fp12.finalExponentiate(bls.fields.Fp12.mul(eGS, ePHm));
    ```
    
We identified that we could just pass a flag to the pairing operation like so: `bls.pairing(S, G, true)` so this could probably be closed (unless others want to use the `finalExponentiate` separately from pairing for some reason)

**Comment by paulmillr** [comment]
updated docs 6220534
