### ISSUE TITLE
u coordinate expected 56 bytes, got 57

### ISSUE THREAD

**Issue by Icehunter** [paulmillr/noble-curves#66]
Here's an example in codesandbox:

https://codesandbox.io/s/morning-currying-59ptsd?file=/src/App.tsx

I've also tried this in node v18 and v20 with the same issue running with ts-node.

Perhaps I'm doing something incorrect?

My use case:

Users have pub/priv keys generated by this library -> convereted to hex -> encryped -> stored.

After that they use ECDH to save and exchange data.

**Comment by Icehunter** [comment]
It looks like the example was a little off, unless this is wrong but:

```jsx
const priv = ed448.utils.randomPrivateKey();
const pub = x448.getPublicKey(priv);

x448.getSharedSecret(priv, pub);
```

That works, if using x448 to get the public and ed448 to get private.

**Comment by paulmillr** [comment]
ed448 and x448 keys are NOT interchangeable

```
const priv = x448.utils.randomPrivateKey();
const pub = x448.getPublicKey(priv);
x448.getSharedSecret(priv, pub);
x448.getPublicKey(priv);
```

**Comment by Icehunter** [comment]
Makes much more sense thank you!
