### ISSUE TITLE
ECDH

### ISSUE THREAD

**Issue by parviz-mv** [paulmillr/noble-curves#67]
Hi mr. @paulmillr ! I have question about ECDH. I'm working on implementation of  [ECDH-ES+A256KW](https://identity.foundation/didcomm-messaging/spec/#key-wrapping-algorithms) key wrapping algorithm, and found your library. Tell me please, for ECDH, can I use your library (p256,p384,p521 and X25519), is it suitable for me?

**Comment by paulmillr** [comment]
yes

**Comment by parviz-mv** [comment]
thanks!
