### ISSUE TITLE
When using endomorphism, should jacobi first be converted to affine？

### ISSUE THREAD

**Issue by JiaqiBLSM** [paulmillr/noble-curves#69]
$\lambda P = (\beta x \bmod p, y)$.  But the endomorphism I saw in the [Blog](https://paulmillr.com/posts/noble-secp256k1-fast-ecc/) is: k2p = new JacobianPoint(mod(k2p.x * CURVE.beta), k2p.y, k2p.z);

**Comment by paulmillr** [comment]
No, it works fine in jacobi, all tests pass correctly.
