### ISSUE TITLE
Signature export

### ISSUE THREAD

**Issue by dhruvkelawala** [paulmillr/noble-curves#7]
https://github.com/paulmillr/noble-curves/blob/65d7256b9e8ecffdf57bfe61b65158a21ac348c9/src/abstract/weierstrass.ts#L767

Why are we exporting Signature of type `SignatureConstructor` and not `Signature` class?

https://github.com/paulmillr/noble-curves/blob/65d7256b9e8ecffdf57bfe61b65158a21ac348c9/src/abstract/weierstrass.ts#L928

This breaks the type inference (when being explicit) using `sign` method in stark.ts because it returns `SignatureType` which needs to be imported from `weierstrass.ts`. I think Signature Class should be exported from `weierstrass.ts` instead of SignatureConstructor

**Comment by paulmillr** [comment]
Class can't be exported. It's dynamically generated.

**Comment by dhruvkelawala** [comment]
But is it possible to export a better typing than SignatureConstructor?

**Comment by paulmillr** [comment]
Can you provide a code that shows how is it broken?

**Comment by paulmillr** [comment]
<img width="566" alt="shot" src="https://user-images.githubusercontent.com/574696/210128532-38b1fc5c-6472-4ff6-92a9-d29b266e5829.png">

Seems fine to me.

**Comment by dhruvkelawala** [comment]
<img width="1296" alt="Screenshot 2023-01-02 at 19 29 55" src="https://user-images.githubusercontent.com/50968441/210272003-ab2aea2b-948a-4491-bf99-59282598cdd7.png">

This is the issue when trying to be explicit about `Signature` return type
