### ISSUE TITLE
bls12-381 verify method with G2 curve not working

### ISSUE THREAD

**Issue by parviz-mv** [paulmillr/noble-curves#76]
Hi! I'm trying to verify the created signature with the bls12-381 G2 curve, but I'm encountering the following error:                                                                                         
`Error: bad point: equation left != right` .

First, I generate a key pair, then create a signature using the private key. After that, I attempt to verify the signature using the public key:  

```
const privateKey = bls12_381.utils.randomPrivateKey();
const publicKey = bls12_381.G2.ProjectivePoint.fromPrivateKey(privateKey).toRawBytes(true);
const message = Buffer.from("Hello world!").toString("hex");
const signature = bls12_381.sign(message, privateKey);
const isSignatureValid = bls12_381.verify(signature, message, publicKey);

```
Also, in the [documentation](https://github.com/mattrglobal/bbs-signatures/blob/954c72213f3e89bb435222ccff02c193581589f9/README.md?plain=1#L140) of @mattrglobal/bbs-signatures, it is stated that the length of the signature must be 112 bytes for the G2 curve. However, I am getting 96 bytes.

Everything works fine when using the G1 curve. However, I suspect that the implementation for G2 is not yet available. Could you please confirm?

**Comment by parviz-mv** [comment]
@paulmillr thank you for response. I mean can I create signature using `G2` key as public key? Is not supported at all or just not supported by library?

I am confused by another BLS/BBS implementation which is using `G2` public key for signing:

| Element     | Size Equation                        |
| ----------- | ------------------------------------ |
| Private Key | F                                    |
| Public Key  | G2                                   |
| Signature   | G1 + 2\*F                            |
| Proof       | 5*G1 + (4 + no_of_hidden_messages)*F |

**Comment by paulmillr** [comment]
G1 is used for public keys, G2 is used for signatures
If you need G1 sigs and G2 pubkeys, we don't support it: see #74
