### ISSUE TITLE
noble-curve.js is missing edwardsToMontogomeryPriv and -Pub? 

### ISSUE THREAD

**Issue by VeronikaSemmelrock** [paulmillr/noble-curves#78]
Hello, 
I switched from noble-ed25519 to using noble-curves, because in the new update of noble-ed25519 the feature getSharedSecret was removed. 
I am trying to get x25519.getSharedSecret to work by using edwardsToMontgomeryPriv and edwardsToMontgomeryPub for converting the ed25519 keys. 
I need to use the standalone noble-curve.js but the functions do not seem to be contained there. 

Thank you for your help!

**Comment by paulmillr** [comment]
updated the release and added the function.

https://github.com/paulmillr/noble-curves/releases/tag/1.2.0
