### ISSUE TITLE
why secp256k1.utils.randomPrivateKey() produce a 32 bytes key?

### ISSUE THREAD

**Issue by zzzh** [paulmillr/noble-curves#88]
And so do the secp256k1.getPublicKey().
Shouldn't they produce keys of 64 bytes?

**Comment by b35363** [comment]
nope public keys in Elliptic curve cryptography is just point coordinates,
You can encode it in PEM or usually SEC format, 

66 bytes for uncompressed public key  
 - 0x04 + x[32] + y[32]

You can also compress it to produce 33 bytes public keys, only using one coordinate and parity

33 bytes for compressed public key 
 - 0x02 + x[32] when y is even
 - 0x03 + x[32] when y is odd

https://www.secg.org/sec1-v2.pdf

**Comment by zzzh** [comment]
I see, for my case, I need 64 bytes of the uncompressed public key to talk to another program that uses another library in another language..
 So, is there a way in this lib to uncompress it?
