### ISSUE TITLE
Ability to multiply Point by CURVE.n

### ISSUE THREAD

**Issue by terribleplan** [paulmillr/noble-curves#9]
I am working on implementing the SPAKE2+ draft using `@noble/curves` and am running into a little trouble when implementing their [Algorithm used for Point Generation](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-spake2-26#name-algorithm-used-for-point-ge). The reference implementation performs a check on generated point (`p != ec.zero_elem() and p * p.l() == ec.zero_elem()`). In order to reproduce their results I have had to resort to some pretty ugly hacks (creating a `wnaf` instance for each curve, wrapping/unwrapping `ProjectivePoint` or `ExtendedPoint` for the various curves, and calling `wnaf.unsafeLadder` directly). [RFC 8032](https://www.rfc-editor.org/rfc/rfc8032#appendix-A)'s example python implementation handles this operation without objection.

Is there a better way of doing this that I am not seeing? Are the authors of SPAKE2+ doing something odd?

**Comment by paulmillr** [comment]
You are looking for torsion-free points.

The functionality can be achieved by executing .isTorsionFree() on an edwards Point. 

I would suggest using Ristretto as a proper abstraction for this case. Multiplying by cofactor is extremely expensive and slow.

**Comment by paulmillr** [comment]
Just understood that we had isTorsionFree() broken for the last months. Will fix it.

**Comment by paulmillr** [comment]
Fixed, use 0.5.2 and `p.isTorsionFree()`
