### ISSUE TITLE
recoverPublicKey not in your library ?

### ISSUE THREAD

**Issue by L1xus** [paulmillr/noble-curves#97]
I want to recover the publickey from a signature using the guide you provided in your README  ```sig.recoverPublicKey(msg);``` but I get the error saying ```TypeError: Signature.recoverPublicKey is not a function``` .

I checked the library and I couldn't find it!

is there any other way to recover the publicKey from the signature ?

**Comment by paulmillr** [comment]
read README more carefully, including comments: https://github.com/paulmillr/noble-curves#ecdsa-public-key-recovery--extra-entropy
