### ISSUE TITLE
Release @noble/curves 🙏

### ISSUE THREAD

**Issue by krpeacock** [paulmillr/noble-curves#98]
Hi @paulmillr, I don't know what your normal release cadence is, but I would like to build with the bls `verifyShortSignature` method that is present on `main` but not yet released.

I've packed it and tested it manually, but it would be nice to point to an official version in my library!

**Comment by paulmillr** [comment]
The cadence is quarterly, it'll be coming soon.

**Comment by aulneau** [comment]
wonder if beta channels might help?

**Comment by paulmillr** [comment]
plan for the next days:

- release hashes, ciphers, curves
- release scure updates

**Comment by krpeacock** [comment]
Resolved with 1.3.0!
